{% set name = "strip-hints" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

  sha256: 307c2bd147cd35997c8ed2e9a3bdca48ad9c9617e04ea46599095201b4ce998f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - strip-hints = strip_hints.strip_hints_main:process_command_line

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - strip_hints

about:
  home: https://github.com/simplejson/simplejson
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Function and command-line program to strip Python type hints.

  description: |
    This package provides a command-line command and a corresponding importable function that strips type hints
    from Python code files. The stripping process leaves runnable code, assuming the rest of the code is runnable
     in the interpreter version. The program tries to make as few changes as possible to the processed code so that
      line and column numbers in error messages for the processed code file also correspond to those for
      the original code file. In most cases, with the default options, both the line and column numbers are preserved.
  dev_url: https://github.com/abarker/strip-hints

extra:
  recipe-maintainers:
    - tanguycdls
    - radcheb
